name: Build and push

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rofleksey/go-builder
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Gitea
        uses: docker/login-action@v3
        with:
          registry: git.tchvrs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: ''
          cache-to: ''
          tags: git.tchvrs.com/touchverse/termagent:${{github.ref_name}},git.tchvrs.com/touchverse/termagent:latest
